#!/usr/bin/env ruby
require 'pathname'
require 'fileutils'
include FileUtils

APP_ROOT = Pathname.new File.expand_path('../', __FILE__)

chdir APP_ROOT do
  system('clear')
  puts "\n------ Starting application server (sinatra) ------"
  system('ruby ./app/application.rb')
end